[package]
name = "lausch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
byteorder = "1.4.3"
cached-path = "0.6.1"
clap = { version = "4.2.1", features = ["derive"] }
cpal = "0.15.2"
crossbeam-channel = "0.5.8"
dirs = "5.0.0"
itertools = "0.11.0"
regex = "1.7.3"
tfc = "0.6.2"
tracing = "0.1.37"
url = "2.3.1"
whisper-rs = "0.5.0"
